name: General Bug Report
description: Create a report to help us improve
title: "[Bug]: "
labels: ["bug"]
assignees:
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the bug _Опишите баг_
      description: "A clear and concise description of what the bug is.\n_Четкое и лаконичное описания ошибки_"
      placeholder: Tell us what you see! _Напишите нам что произошло_
      value: ""
    validations:
      required: true
  - type: textarea
    id: to-reproduce
    attributes:
      label: To Reproduce _Для воспроизведения_
      description: "Steps to reproduce the behavior:\n_Что нужно сделать для воспроизведения ошибки:_"
      placeholder: Write steps you did to cause the bug _Напишите шаги, которые привели к ошибке_
      value: "1. "
    validations:
      required: false
  - type: textarea
    id: excepted-behavior
    attributes:
      label: Expected behavior _Ожидаемое поведение_
      description: "A clear and concise description of what you expected to happen.\n_Четкое и лаконичное описание ожидаемого результата действий_"
      placeholder: Write what did you except _Напишите чего вы ожидали_
      value: ""
    validations:
      required: false
  - type: imagepicker
    id: screenshot
    attributes:
      label: Screenshots _Скриншоты_
      description: "If applicable, add screenshots to help explain your problem.\n_Если возможно, прикрепите скриншот проблемы_"
    validations:
      required: false
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on? _При использовании каких браузерах возникает проблема?_
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: dropdown
    id: os
    attributes:
      label: What OS are you seeing the problem on? _Какую ОС вы используете_
      multiple: true
      options:
        - Linux
        - Windows
        - Mac OS
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context _Дополнительная информация_
      description: "Add any other context about the problem here.\n_Впишите сюда любую другую информацию о контексте возникновения проблемы_"
      placeholder: Tell us what you see! _Напишите нам что произошло_
      value: ""
    validations:
      required: true
