# Generated by Django 4.1.3 on 2022-12-12 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_lateremuser_lateremassignment_lateremgroup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LateremCategoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('root_category', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LateremGroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_group_admin', models.BooleanField(default=False)),
                ('can_manage_group_data', models.BooleanField(default=False)),
                ('can_manage_members', models.BooleanField(default=False)),
                ('can_view_members', models.BooleanField(default=True)),
                ('can_manage_permissions', models.BooleanField(default=False)),
                ('can_add_members', models.BooleanField(default=False)),
                ('can_assign_works', models.BooleanField(default=False)),
                ('can_examine_solutions', models.BooleanField(default=False)),
                ('can_solve_works', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LateremSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verdict', models.CharField(max_length=2)),
                ('timestamp', models.DateTimeField()),
                ('answers', models.TextField()),
                ('teacher_comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LateremTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('task_type', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='LateremWorkCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('root_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_app.lateremcategorycategory')),
            ],
        ),
        migrations.RemoveField(
            model_name='lateremgroup',
            name='owners',
        ),
        migrations.RemoveField(
            model_name='lateremgroup',
            name='users',
        ),
        migrations.RemoveField(
            model_name='lateremuser',
            name='is_teacher',
        ),
        migrations.RemoveField(
            model_name='lateremwork',
            name='task_names',
        ),
        migrations.RemoveField(
            model_name='lateremwork',
            name='task_types',
        ),
        migrations.AddField(
            model_name='lateremassignment',
            name='teacher',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assigner', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lateremgroup',
            name='can_manage_groups',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lateremgroup',
            name='can_manage_users',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lateremgroup',
            name='can_manage_works',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lateremgroup',
            name='can_solve_tasks',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lateremuser',
            name='settings',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lateremwork',
            name='author',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lateremwork',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lateremassignment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lateremgroup',
            name='name',
            field=models.CharField(max_length=128, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='lateremwork',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.DeleteModel(
            name='LateremRecord',
        ),
        migrations.AddField(
            model_name='lateremtask',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.lateremwork'),
        ),
        migrations.AddField(
            model_name='lateremsolution',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.lateremtask'),
        ),
        migrations.AddField(
            model_name='lateremsolution',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lateremgroupmembership',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.lateremgroup'),
        ),
        migrations.AddField(
            model_name='lateremgroupmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lateremwork',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_app.lateremworkcategory'),
        ),
    ]
