# Generated by Django 4.1.3 on 2023-02-12 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0004_lateremgroupmembership_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='lateremtask',
            name='field_overrides',
            field=models.TextField(default='{}'),
        ),
        migrations.AlterField(
            model_name='lateremuser',
            name='settings',
            field=models.TextField(default='{}'),
        ),
        migrations.CreateModel(
            name='LateremTaskTemplate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='lateremtask',
            name='task_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.lateremtasktemplate'),
        ),
    ]
