# Generated by Django 4.1.3 on 2023-03-06 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0007_remove_laterembugreport_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laterembugreport',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
