# Generated by Django 4.1.3 on 2023-03-08 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0008_laterembugreport_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='lateremtasktemplate',
            name='birthname',
            field=models.CharField(default='default', max_length=128),
            preserve_default=False,
        ),
    ]
