# Generated by Django 4.1.6 on 2023-03-15 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_app", "0009_lateremtasktemplate_birthname"),
    ]

    operations = [
        migrations.AddField(
            model_name="lateremtask",
            name="order",
            field=models.IntegerField(default=0),
        ),
    ]
