# Generated by Django 4.1.3 on 2023-03-30 02:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0011_alter_lateremassignment_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laterembugreport',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
